const cities = {
  kyiv: "Київ",
  Kharkiv: "Харків",
  Odesa: "Одеса",
  Dnipro: "Дніпро",
  Donetsk: "Донецьк",
  Zaporizhzhia: "Запоріжжя",
  Lviv: "Львів",
  Mykolaiv: "Миколаїв",
  Mariupol: "Маріуполь",
  Vinnytsia: "Вінниця",
  Sevastopol: "Севастополь",
  Simferopol: "Сімферополь",
  Chernihiv: "Чернігів",
  Kherson: "Херсон",
  Poltava: "Полтава",
  Khmelnytskyi: "Хмельницький",
  Cherkasy: "Черкаси",
  Chernivtsi: "Чернівці",
  Zhytomyr: "Житомир",
  Sumy: "Суми",
  Rivne: "Рівне",
  Ternopil: "Тернопіль",
  Kropyvnytskyi: "Кропивницький",
  Kremenchuk: "Кременчук",
  Lutsk: "Луцьк",
};


export default cities
